- name: Install and configure webserver
  hosts: webservers
  tasks:
  - name: Install httpd
    yum: 
      name: httpd
      state: present
  - name: service start
    service:
      name: httpd
      state: started
      enabled: yes
